### PR TITLE
Hud

### PR DESCRIPTION
**Pull request by cwalker012**
Basic Hud for health. Appears during dialogue. No state yet that will decrement health.

### CODE REVIEW

**Comment by benhigh98** [comment]
side-shot-Korean-corn-dog-thumbnail

**Comment by cwalker012** [comment]
Looks good to me

**Comment by cwalker012** [comment]
DOn't merge

**Comment by Sarah-Salad** [comment]
looks bean to me

**Comment by cwalker012** [comment]
@JacobStauch please review

**Review by JacobStauch — APPROVED** [review]

**Pull request merged**
